// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBchZwLCPVnaLFGGT4MtENo0vsZp2KDGhU',
    appId: '1:284529445489:web:0cef9dc156d675c1c669d0',
    messagingSenderId: '284529445489',
    projectId: 'farmbro-b77f1',
    authDomain: 'farmbro-b77f1.firebaseapp.com',
    storageBucket: 'farmbro-b77f1.appspot.com',
    measurementId: 'G-LQSNL3JPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wYnVtRX-IA3oDtWa0gcddhXbL-AjlP0',
    appId: '1:284529445489:android:0f84d233e04fdb51c669d0',
    messagingSenderId: '284529445489',
    projectId: 'farmbro-b77f1',
    storageBucket: 'farmbro-b77f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgdeKE5ROmd4m5b0rSIKOXft7WAP7V5qo',
    appId: '1:284529445489:ios:55ea58a588ead96ec669d0',
    messagingSenderId: '284529445489',
    projectId: 'farmbro-b77f1',
    storageBucket: 'farmbro-b77f1.appspot.com',
    iosBundleId: 'com.example.farmbroapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgdeKE5ROmd4m5b0rSIKOXft7WAP7V5qo',
    appId: '1:284529445489:ios:55ea58a588ead96ec669d0',
    messagingSenderId: '284529445489',
    projectId: 'farmbro-b77f1',
    storageBucket: 'farmbro-b77f1.appspot.com',
    iosBundleId: 'com.example.farmbroapk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBchZwLCPVnaLFGGT4MtENo0vsZp2KDGhU',
    appId: '1:284529445489:web:be63a02834940f86c669d0',
    messagingSenderId: '284529445489',
    projectId: 'farmbro-b77f1',
    authDomain: 'farmbro-b77f1.firebaseapp.com',
    storageBucket: 'farmbro-b77f1.appspot.com',
    measurementId: 'G-QXGRFS9JQL',
  );
}
